on:
 push:
   branches: 
     - master  








jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:

      - uses: actions/checkout@v3
        
      - name: 'docker login'
        run: docker login --usernamr ${{ DOCKER_USER }} --password ${{ DOCKER_PASS }} 

      - name: 'building image'
        run: docker build -t ${{ DOCKER_USER }}/image .


      - name : 'pushing'
        run: docker push ${{ DOCKER_USER }}/image

